# Generated by Django 3.1.5 on 2021-04-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='regi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=100)),
                ('usertype', models.CharField(default='customer', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_number', models.CharField(default='', max_length=100)),
                ('room_types', models.CharField(default='', max_length=100)),
                ('price', models.CharField(default='', max_length=100)),
                ('pic', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
