# Generated by Django 3.1.5 on 2021-04-26 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoapp', '0002_auto_20210424_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.CharField(default='', max_length=100)),
                ('date', models.CharField(default='', max_length=100)),
                ('i_d', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoapp.regi')),
                ('r_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoapp.rooms')),
            ],
        ),
    ]
