# Generated by Django 3.1.5 on 2021-04-29 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoapp', '0003_bookon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookon',
            old_name='date',
            new_name='datein',
        ),
        migrations.AddField(
            model_name='bookon',
            name='dateout',
            field=models.CharField(default='', max_length=100),
        ),
    ]
