# Generated by Django 3.1.5 on 2021-04-29 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoapp', '0004_auto_20210429_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='status',
            field=models.CharField(default='', max_length=100),
        ),
    ]
