# Generated by Django 3.1.5 on 2021-05-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoapp', '0005_rooms_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookon',
            name='total',
            field=models.CharField(default='', max_length=100),
        ),
    ]
