# Generated by Django 3.1.5 on 2021-05-07 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoapp', '0006_bookon_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='paym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_d', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoapp.regi')),
                ('r', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoapp.bookon')),
            ],
        ),
    ]
