# Generated by Django 3.1.5 on 2021-05-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoapp', '0007_paym'),
    ]

    operations = [
        migrations.AddField(
            model_name='paym',
            name='payment',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
