# Generated by Django 3.1.5 on 2021-05-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoapp', '0008_paym_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookon',
            name='payment',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
