# Generated by Django 3.1.5 on 2021-05-10 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoapp', '0010_remove_bookon_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookon',
            name='status',
            field=models.CharField(default='', max_length=100),
        ),
    ]
